### ISSUE TITLE
项目文件缺少MyDialog.h和MyDialog.cpp

### ISSUE THREAD

**Issue by RedNose-coder** [IMVector/Remote#2]
准备学习这个系统，编译时发现缺少MyDialog.h和MyDialog.cpp文件，作者大大可否补充一下

**Comment by IMVector** [comment]
> 准备学习这个系统，编译时发现缺少MyDialog.h和MyDialog.cpp文件，作者大大可否补充一下

您好，您试下切换到win+mac 分支是否可以编译？我当时编译的时候使用的vs2015，还有一些依赖的本地库如gdal等，如果实在不行的话，我上传了一个18年编译的release版的，电脑上暂时没有相关的环境，还需要您试一下

**Comment by RedNose-coder** [comment]
好的，我试试看，非常感谢！
